# Scientific Configuration for Cannabis PhenoHunter
# Research-backed parameters with literature citations

# Compound Configuration
compounds:
  cannabinoids:
    major:
      - name: "thc"
        full_name: "Delta-9-Tetrahydrocannabinol"
        unit: "percent"
        typical_range: [0.0, 35.0]
        therapeutic_threshold: 10.0

      - name: "cbd"
        full_name: "Cannabidiol"
        unit: "percent"
        typical_range: [0.0, 25.0]
        therapeutic_threshold: 5.0

      - name: "cbg"
        full_name: "Cannabigerol"
        unit: "percent"
        typical_range: [0.0, 2.0]
        therapeutic_threshold: 0.5

      - name: "cbc"
        full_name: "Cannabichromene"
        unit: "percent"
        typical_range: [0.0, 1.5]
        therapeutic_threshold: 0.3

      - name: "cbda"
        full_name: "Cannabidiolic Acid"
        unit: "percent"
        typical_range: [0.0, 5.0]
        therapeutic_threshold: 1.0

    minor:
      - name: "thcv"
        full_name: "Tetrahydrocannabivarin"
        unit: "percent"
        typical_range: [0.0, 2.0]
        therapeutic_threshold: 0.3

      - name: "cbn"
        full_name: "Cannabinol"
        unit: "percent"
        typical_range: [0.0, 3.0]
        therapeutic_threshold: 0.5

      - name: "delta8_thc"
        full_name: "Delta-8-Tetrahydrocannabinol"
        unit: "percent"
        typical_range: [0.0, 1.0]
        therapeutic_threshold: 0.2

      - name: "thca"
        full_name: "Tetrahydrocannabinolic Acid"
        unit: "percent"
        typical_range: [0.0, 30.0]
        therapeutic_threshold: 10.0

  terpenes:
    major:
      - name: "myrcene"
        full_name: "β-Myrcene"
        unit: "percent"
        typical_range: [0.0, 4.0]
        therapeutic_threshold: 0.5

      - name: "limonene"
        full_name: "D-Limonene"
        unit: "percent"
        typical_range: [0.0, 3.5]
        therapeutic_threshold: 0.4

      - name: "pinene"
        full_name: "α-Pinene"
        unit: "percent"
        typical_range: [0.0, 2.5]
        therapeutic_threshold: 0.3

      - name: "linalool"
        full_name: "Linalool"
        unit: "percent"
        typical_range: [0.0, 2.0]
        therapeutic_threshold: 0.3

      - name: "caryophyllene"
        full_name: "β-Caryophyllene"
        unit: "percent"
        typical_range: [0.0, 3.0]
        therapeutic_threshold: 0.4

      - name: "humulene"
        full_name: "α-Humulene"
        unit: "percent"
        typical_range: [0.0, 1.5]
        therapeutic_threshold: 0.2

    minor:
      - name: "terpinolene"
        full_name: "Terpinolene"
        unit: "percent"
        typical_range: [0.0, 1.0]
        therapeutic_threshold: 0.1

      - name: "ocimene"
        full_name: "Ocimene"
        unit: "percent"
        typical_range: [0.0, 1.0]
        therapeutic_threshold: 0.1

      - name: "camphene"
        full_name: "Camphene"
        unit: "percent"
        typical_range: [0.0, 0.5]
        therapeutic_threshold: 0.05

      - name: "bisabolol"
        full_name: "α-Bisabolol"
        unit: "percent"
        typical_range: [0.0, 1.0]
        therapeutic_threshold: 0.1

# Effect Prediction Models
# Based on peer-reviewed literature (Russo 2011, Booth & Bohlmann 2019)
effects:
  analgesic:
    description: "Pain relief"
    primary_compounds:
      - compound: "cbd"
        coefficient: 0.45
        evidence: "Russo EB. (2008). Clinical endocannabinoid deficiency. Neuroendocrinol Lett."

      - compound: "thc"
        coefficient: 0.25
        evidence: "Russo EB. (2008). Cannabinoids in pain treatment"

      - compound: "myrcene"
        coefficient: 0.15
        evidence: "Russo EB. (2011). Taming THC. Br J Pharmacol."

      - compound: "caryophyllene"
        coefficient: 0.15
        evidence: "Klauke et al. (2014). CB2 receptor-selective cannabinoids"

    interaction_terms:
      - compounds: ["cbd", "myrcene"]
        coefficient: 0.08
        interaction_type: "synergistic"

    threshold_probability: 0.6
    confidence_requirement: 0.70

  anxiolytic:
    description: "Anxiety reduction"
    primary_compounds:
      - compound: "cbd"
        coefficient: 0.50
        evidence: "Blessing et al. (2015). Cannabidiol as treatment for anxiety disorders"

      - compound: "linalool"
        coefficient: 0.25
        evidence: "Guzmán-Gutiérrez et al. (2012). Linalool and β-pinene exert anxiolytic-like effects"

      - compound: "limonene"
        coefficient: 0.15
        evidence: "Lima et al. (2013). Anxiolytic-like activity of limonene"

      - compound: "myrcene"
        coefficient: 0.10
        evidence: "Russo EB. (2011). Taming THC"

    interaction_terms:
      - compounds: ["cbd", "linalool"]
        coefficient: 0.12
        interaction_type: "synergistic"

    threshold_probability: 0.65
    confidence_requirement: 0.75

  sedative:
    description: "Sleep promotion and sedation"
    primary_compounds:
      - compound: "myrcene"
        coefficient: 0.35
        evidence: "Russo EB. (2011). Myrcene sedative effects"

      - compound: "linalool"
        coefficient: 0.25
        evidence: "Buchbauer et al. (1993). Fragrance compounds and essential oils with sedative effects"

      - compound: "cbn"
        coefficient: 0.20
        evidence: "Russo & Guy (2006). CBN as sedative cannabinoid"

      - compound: "caryophyllene"
        coefficient: 0.10
        evidence: "Gertsch et al. (2008). Beta-caryophyllene is a dietary cannabinoid"

      - compound: "thc"
        coefficient: 0.10
        evidence: "Nicholson et al. (2004). Effect of THC on sleep"

    interaction_terms:
      - compounds: ["myrcene", "linalool"]
        coefficient: 0.15
        interaction_type: "synergistic"

    threshold_probability: 0.55
    confidence_requirement: 0.70

  anti_inflammatory:
    description: "Inflammation reduction"
    primary_compounds:
      - compound: "cbd"
        coefficient: 0.35
        evidence: "Burstein (2015). Cannabidiol (CBD) and its analogs: anti-inflammatory effects"

      - compound: "caryophyllene"
        coefficient: 0.30
        evidence: "Fidyt et al. (2016). β-caryophyllene and β-caryophyllene oxide"

      - compound: "humulene"
        coefficient: 0.20
        evidence: "Rogerio et al. (2009). α-Humulene reduces inflammatory mediators"

      - compound: "cbc"
        coefficient: 0.15
        evidence: "Romano et al. (2013). Cannabichromene anti-inflammatory effects"

    interaction_terms:
      - compounds: ["caryophyllene", "humulene"]
        coefficient: 0.10
        interaction_type: "synergistic"

      - compounds: ["cbd", "caryophyllene"]
        coefficient: 0.08
        interaction_type: "synergistic"

    threshold_probability: 0.60
    confidence_requirement: 0.72

  neuroprotective:
    description: "Neuroprotection and cognitive support"
    primary_compounds:
      - compound: "cbd"
        coefficient: 0.40
        evidence: "Fernández-Ruiz et al. (2013). Cannabidiol for neurodegenerative disorders"

      - compound: "pinene"
        coefficient: 0.25
        evidence: "Bonesi et al. (2010). α-Pinene acetylcholinesterase inhibitory activity"

      - compound: "cbg"
        coefficient: 0.20
        evidence: "Valdeolivas et al. (2015). Neuroprotective properties of CBG"

      - compound: "limonene"
        coefficient: 0.15
        evidence: "Yoon et al. (2010). Limonene neuroprotective effects"

    interaction_terms:
      - compounds: ["cbd", "pinene"]
        coefficient: 0.10
        interaction_type: "synergistic"

    threshold_probability: 0.58
    confidence_requirement: 0.68

  appetite_stimulant:
    description: "Appetite stimulation"
    primary_compounds:
      - compound: "thc"
        coefficient: 0.55
        evidence: "Kirkham (2005). Endocannabinoids in the control of appetite"

      - compound: "caryophyllene"
        coefficient: 0.20
        evidence: "Turcotte et al. (2016). CB2 receptor agonist effects on feeding"

      - compound: "myrcene"
        coefficient: 0.15
        evidence: "Russo EB. (2011). Myrcene sedative/muscle relaxant effects"

      - compound: "humulene"
        coefficient: -0.10
        evidence: "Rogerio et al. (2009). Humulene may suppress appetite"

    interaction_terms:
      - compounds: ["thc", "myrcene"]
        coefficient: 0.08
        interaction_type: "synergistic"

    threshold_probability: 0.62
    confidence_requirement: 0.75

# Model Architecture Configuration
model:
  vae:
    input_dim: 20  # Will be set dynamically based on compound selection
    latent_dim: 8
    hidden_layers: [32, 16]
    dropout_rate: 0.15
    activation: "relu"
    learning_rate: 0.001
    weight_decay: 0.0001
    beta: 1.0  # KL divergence weight
    epochs: 500
    batch_size: 16
    early_stopping_patience: 50

  ensemble:
    n_models: 5
    voting: "soft"

  cross_validation:
    n_splits: 5
    shuffle: True
    random_state: 42

# Data Validation Rules
validation:
  outlier_detection:
    method: "isolation_forest"
    contamination: 0.1

  quality_checks:
    min_total_cannabinoids: 0.1
    max_total_cannabinoids: 50.0
    min_total_terpenes: 0.0
    max_total_terpenes: 10.0

  missing_data:
    max_missing_fraction: 0.3
    imputation_method: "median"

# Breeding Parameters
breeding:
  genetic_variance:
    min_noise_factor: 0.02
    max_noise_factor: 0.10

  parent_influence:
    default_main_weight: 0.6
    min_weight: 0.4
    max_weight: 0.9

  stability_threshold: 0.75
  diversity_importance: 0.30

# Uncertainty Quantification
uncertainty:
  monte_carlo_samples: 1000
  confidence_level: 0.95
  bootstrap_iterations: 500

# Logging and Reproducibility
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

reproducibility:
  random_seed: 42
  deterministic_mode: True
